package com.example.netflix_final.models

data class ActorModel(
    val name: String,
    val characterName: String? = null,
    val image: String? = null
)

val actorList = listOf(
    ActorModel("Timothée Chalamet", "Paul Atreides", "https://media.themoviedb.org/t/p/w500/BE2sdjpgsa2rNTFa66f7upkaOP.jpg"),
    ActorModel("Rebecca Ferguson", "Lady Jessica", "https://media.themoviedb.org/t/p/w500/lJloTOheuQSirSLXNA3JHsrMNfH.jpg"),
    ActorModel("Oscar Isaac", "Duke Leto Atreides", "https://m.media-amazon.com/images/M/MV5BMTQ2ODE2NDQ5OF5BMl5BanBnXkFtZTcwOTU3OTM1OQ@@._V1_FMjpg_UX1000_.jpg"),
    ActorModel("Josh Brolin", "Gurney Halleck", "https://media.themoviedb.org/t/p/w500/sX2etBbIkxRaCsATyw5ZpOVMPTD.jpg"),
    ActorModel("Stellan Skarsgård", "Baron Vladimir Harkonnen", "https://media.themoviedb.org/t/p/w500/x78BtYHElirO7Iw8bL4m8CnzRDc.jpg"),
    ActorModel("Dave Bautista", "Glossu Rabban", "https://image.tmdb.org/t/p/original/fB8C7M6Am956NQW10ltqX3kXo2W.jpg"),
    ActorModel("Zendaya", "Chani", "https://image.tmdb.org/t/p/original/3WdOloHpjtjL96uVOhFRRCcYSwq.jpg"),
    ActorModel("Javier Bardem", "Stilgar", "https://media.themoviedb.org/t/p/w500/IShnFg6ijWhpbu29dFBd9PtqQg.jpg"),
    ActorModel("Austin Butler", "Feyd-Rautha Harkonnen", "https://media.themoviedb.org/t/p/w500/jn63A9goIetyvJt5DTHypjk33ip.jpg"),
    ActorModel("Florence Pugh", "Princess Irulan", "https://media.themoviedb.org/t/p/w500/f8e41Oon18FiEZr4zgyJDVUqOeh.jpg"),
    ActorModel("Christopher Walken", "Emperor Shaddam IV", "https://media.themoviedb.org/t/p/w500/ApgDL7nudR9T2GpjCG4vESgymO2.jpg"),
    ActorModel("Léa Seydoux", "Lady Margot Fenring", "https://media.themoviedb.org/t/p/w500/tUfoM95x70Qsb1ElClPSpSrZQ2v.jpg"),
    ActorModel("Robert Downey Jr.", "Tony Stark / Iron Man", "https://image.tmdb.org/t/p/original/im9SAqJPZKEbVZGmjXuLI4O7RvM.jpg"),
    ActorModel("Chris Evans", "Steve Rogers / Captain America", "https://image.tmdb.org/t/p/w500/3bOGNsHlrswhyW79uvIHH1V43JI.jpg"),
    ActorModel("Mark Ruffalo", "Bruce Banner / Hulk", "https://media.themoviedb.org/t/p/w500/5GilHMOt5PAQh6rlUKZzGmaKEI7.jpg"),
    ActorModel("Chris Hemsworth", "Thor", "https://image.tmdb.org/t/p/original/tlkDiLn2G75Xr7m1ybK8QFzZBso.jpg"),
    ActorModel("Scarlett Johansson", "Natasha Romanoff / Black Widow", "https://image.tmdb.org/t/p/original/6bBCPmc55gzP7TR9Th4WbykrYd0.jpg"),
    ActorModel("Jeremy Renner", "Clint Barton / Hawkeye", "https://media.themoviedb.org/t/p/w500/yB84D1neTYXfWBaV0QOE9RF2VCu.jpg"),
    ActorModel("Don Cheadle", "James Rhodes / War Machine", "https://tr.web.img4.acsta.net/c_310_420/pictures/15/11/24/16/49/154499.jpg"),
    ActorModel("Paul Rudd", "Scott Lang / Ant-Man", "https://cdn.britannica.com/74/220474-050-087FF31B/Paul-Rudd-2018.jpg"),
    ActorModel("Brie Larson", "Carol Danvers / Captain Marvel", "https://image.tmdb.org/t/p/original/nTABNG8Sw4EVN3xodn2JBdEmBqv.jpg"),
    ActorModel("Chris Pratt", "Peter Quill / Star-Lord", "https://cdn.britannica.com/48/216648-050-4A42C937/American-actor-Chris-Pratt-2020.jpg"),
    ActorModel("Zoe Saldana", "Gamora", "https://image.vip.de/23272682/t/pC/v2/w960/r0/-/zoe-saldana-t4653-jpg--topic-image-4653-.jpg"),
    ActorModel("Bradley Cooper", "Rocket (voice)", "https://cdn.britannica.com/57/199057-050-CCE5410A/Bradley-Cooper-2008.jpg"),
    ActorModel("Vin Diesel", "Groot (voice)", "https://m.media-amazon.com/images/M/MV5BMjExNzA4MDYxN15BMl5BanBnXkFtZTcwOTI1MDAxOQ@@._V1_.jpg"),
    ActorModel("Karen Gillan", "Nebula", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/572089_v9_bd.jpg"),
    ActorModel("Tom Holland", "Peter Parker / Spider-Man", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/733885_v9_bc.jpg"),
    ActorModel("Sebastian Stan", "James Buchanan Barnes / Winter Soldier", "https://mr.comingsoon.it/imgdb/persone/208890_ico.jpg"),
    ActorModel("Anthony Mackie", "Sam Wilson / Falcon", "https://media.themoviedb.org/t/p/w500/kfTwOYr3iUucmYz8kPjhYy07G2Z.jpg"),
    ActorModel("Elizabeth Olsen", "Wanda Maximoff / Scarlet Witch", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/620481_v9_bc.jpg"),
    ActorModel("Paul Bettany", "Vision", "https://i.pinimg.com/236x/58/b3/1c/58b31c474448c52f22d18bb882bb5f8f.jpg"),
    ActorModel("Benedict Cumberbatch", "Stephen Strange / Doctor Strange", "https://m.media-amazon.com/images/M/MV5BMjE0MDkzMDQwOF5BMl5BanBnXkFtZTgwOTE1Mjg1MzE@._V1_.jpg"),
    ActorModel("Chadwick Boseman", "T'Challa / Black Panther", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/492157_v9_bd.jpg"),
    ActorModel("Danai Gurira", "Okoye", "https://m.media-amazon.com/images/M/MV5BNjYyNjg1OTU1M15BMl5BanBnXkFtZTgwNzYyNTkzMDI@._V1_FMjpg_UX1000_.jpg"),
    ActorModel("Letitia Wright", "Shuri", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/643922_v9_bb.jpg"),
    ActorModel("Pom Klementieff", "Mantis", "https://media.themoviedb.org/t/p/w500/hfUKAI2kXTMMWjno0i4sLPJud5N.jpg"),
    ActorModel("Tom Vaughan-Lawlor", "Ebony Maw", "https://www.thesun.ie/wp-content/uploads/sites/3/2024/03/tom-vaughan-lawlor-attends-special-889611962.jpg"),
    ActorModel("Terry Notary", "Cull Obsidian", "https://media.themoviedb.org/t/p/w500/nYs1Sd11czZNwcDyUYdHPwHHIRO.jpg"),
    ActorModel("Michael James Shaw", "Corvus Glaive", "https://tvline.com/wp-content/uploads/2021/03/michael-james-shaw-walking-dead.jpg"),
    ActorModel("Winston Duke", "M'Baku", "https://pbs.twimg.com/profile_images/1447807826856980481/vBNK-mmm_400x400.jpg"),
    ActorModel("Benedict Wong", "Wong", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/290344_v9_bd.jpg"),
    ActorModel("Jacob Batalon", "Ned Leeds", "https://media.themoviedb.org/t/p/w500/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg"),
    ActorModel("Jon Favreau", "Happy Hogan", "https://pyxis.nymag.com/v1/imgs/b27/deb/b682459d71aa9bc0dc390ea6611db5e1ab-02-jon-favreau.jpg"),
    ActorModel("Jeremy Renner", "Clint Barton / Hawkeye", "https://media.themoviedb.org/t/p/w500/yB84D1neTYXfWBaV0QOE9RF2VCu.jpg"),
    ActorModel("Tom Hiddleston", "Loki", "https://media.themoviedb.org/t/p/w500/mclHxMm8aPlCPKptP67257F5GPo.jpg"),
    ActorModel("Samuel L. Jackson", "Nick Fury", "https://image.tmdb.org/t/p/original/jv4zXZmZZonC3ub6f2SSLGI048s.jpg"),
    ActorModel("Clark Gregg", "Phil Coulson", "https://media.themoviedb.org/t/p/w500/nbxFbr2SaF4Sdc6HdsF193GInvJ.jpg"),
    ActorModel("Cobie Smulders", "Maria Hill", "https://image.tmdb.org/t/p/original/jAz6lukhFNt8AGuyZZXiqBCZwRe.jpg"),
    ActorModel("Gwyneth Paltrow", "Pepper Potts", "https://image.tmdb.org/t/p/original/6bBCPmc55gzP7TR9Th4WbykrYd0.jpg"),
    ActorModel("Sam Worthington", "Jake Sully", "https://media.themoviedb.org/t/p/w500/mflBcox36s9ZPbsZPVOuhf6axaJ.jpg"),
    ActorModel("Sigourney Weaver", "Dr. Grace Augustine", "https://hips.hearstapps.com/hmg-prod/images/gettyimages-1207518040.jpg"),
    ActorModel("Stephen Lang", "Colonel Miles Quaritch", "https://upload.wikimedia.org/wikipedia/commons/a/a5/Stephen_Lang_2014.jpg"),
    ActorModel("Michelle Rodriguez", "Trudy Chacon", "https://images.mubicdn.net/images/cast_member/23070/cache-2969-1557516196/image-w856.jpg"),
    ActorModel("Giovanni Ribisi", "Parker Selfridge", "image"),
    ActorModel("Joel David Moore", "Norm Spellman", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/157698_v9_bc.jpg"),
    ActorModel("CCH Pounder", "Mo'at", "https://media.themoviedb.org/t/p/w500/c0ey32ObHhJIQVQYqGejaxOS23x.jpg"),
    ActorModel("Wes Studi", "Eytukan", "https://nmfilmandtvhalloffame.org/app/wp-content/uploads/2019/01/Wes-Studi.jpg"),
    ActorModel("Millie Bobby Brown", "Elodie", "https://images.hellomagazine.com/horizon/landscape/ac99074d225e-gettyimages-1673820862.jpg"),
    ActorModel("Ray Winstone", "Lord Bayford", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/53262_v9_bc.jpg"),
    ActorModel("Angela Bassett", "Lady Bayford", "https://cdn.britannica.com/01/215701-050-DFFB8B71/American-actress-Angela-Bassett-2015.jpg"),
    ActorModel("Nick Robinson", "Prince Henry", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/171360_v9_bd.jpg"),
    ActorModel("Robin Wright", "Queen Isabelle", "https://bookingagentinfo.com/wp-content/uploads/2022/12/Robin-Wright-1.jpg"),
    ActorModel("Brooke Carter", "Floria", "https://cdnph.upi.com/pv/upi/4caa542009ad768a2ee8b61b57ab142f/NETFLIX-DAMSEL-PREMIERE.jpg"),
    ActorModel("Milo Twomey", "King Roderick", "https://bilder.fernsehserien.de/gfx/person_1000/m/milo-twomey-w-893.jpg.jpg"),
    ActorModel("Nicole Joseph", "Princess Victoria", "https://youngentertainmentmag.com/wp-content/uploads/2024/03/IMG_2236.jpg"),
    ActorModel("Margot Robbie", "Barbie", "https://cdn.britannica.com/32/201632-050-66971649/actress-Margot-Robbie-Australian-2018.jpg"),
    ActorModel("Ryan Gosling", "Ken", "https://cdn.britannica.com/93/215393-050-E428CADE/Canadian-actor-musician-Ryan-Gosling-2016.jpg"),
    ActorModel("Issa Rae", "Barbie", "https://m.media-amazon.com/images/M/MV5BMTUyODI3MDg1OF5BMl5BanBnXkFtZTgwMjc5NTc5MDI@._V1_.jpg"),
    ActorModel("Kate McKinnon", "Barbie", "https://hips.hearstapps.com/hmg-prod/images/2013-nbcuniversal-summer-press-day.jpg"),
    ActorModel("Alexandra Shipp", "Barbie", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/564022_v9_bd.jpg"),
    ActorModel("Emma Mackey", "Barbie", "https://images.hellomagazine.com/horizon/square/74eba2370abf-emma-mackey.jpg"),
    ActorModel("Hari Nef", "Barbie", "https://ntvb.tmsimg.com/assets/assets/1144333_v9_bb.jpg"),
    ActorModel("Sharon Rooney", "Barbie", "https://media.themoviedb.org/t/p/w500/s2u8N5UkDDwpxCrtDpordyBMP8n.jpg"),
    ActorModel("Ana Cruz Kayne", "Barbie", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/697663_v9_aa.jpg"),
    ActorModel("Ritu Arya", "Barbie", "https://assets.popbuzz.com/2022/39/ritu-arya-cast-in-barbie-1664278287-view-0.jpg"),
    ActorModel("Dua Lipa", "Barbie", "https://ntvb.tmsimg.com/assets/assets/984374_v9_bd.jpg"),
    ActorModel("Nicola Coughlan", "Barbie", "https://assets.popbuzz.com/2020/51/where-is-nicola-coughlan-from-is-she-irish-1608724400-view-1.jpg"),
    ActorModel("Emerald Fennell", "Midge", "https://d26oc3sg82pgk3.cloudfront.net/files/media/edit/image/54475/article_aligned%402x.jpg"),
    ActorModel("Simu Liu", "Ken", "https://cdn.britannica.com/06/242206-050-E18E3ABD/Simu-Liu-actor-2022.jpg"),
    ActorModel("Kingsley Ben-Adir", "Ken", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/1004352_v9_bb.jpg"),
    ActorModel("Ncuti Gatwa", "Ken", "https://tr.web.img3.acsta.net/pictures/19/01/21/23/28/0249793.jpg"),
    ActorModel("Scott Evans", "Ken", "https://m.media-amazon.com/images/M/MV5BMTY4ODM4NjA3OF5BMl5BanBnXkFtZTgwMTM0NjM0ODE@._V1_.jpg"),
    ActorModel("John Cena", "Ken", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/487578_v9_ba.jpg"),
    ActorModel("Michael Cera", "Allan", "https://m.media-amazon.com/images/M/MV5BNTgyNDgxMjUyOV5BMl5BanBnXkFtZTcwMDYxNzY1OQ@@._V1_.jpg"),
    ActorModel("Helen Mirren", "Narrator", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/74573_v9_bc.jpg"),
    ActorModel("Anthony Mackie", "Sam Wilson / The Falcon", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/308495_v9_bc.jpg"),
    ActorModel("Wyatt Russell", "John Walker / U.S. Agent", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/588425_v9_bc.jpg"),
    ActorModel("Erin Kellyman", "Karli Morgenthau", "https://ntvb.tmsimg.com/assets/assets/994378_v9_bb.jpg"),
    ActorModel("Danny Ramirez", "Joaquin Torres", "https://ntvb.tmsimg.com/assets/assets/927518_v9_bb.jpg"),
    ActorModel("Georges St-Pierre", "Georges Batroc", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Georges_St-Pierre_crop.jpg/220px-Georges_St-Pierre_crop.jpg"),
    ActorModel("Adepero Oduye", "Sarah Wilson", "https://ntvb.tmsimg.com/assets/assets/544892_v9_bc.jpg"),
    ActorModel("Daniel Brühl", "Helmut Zemo", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/260870_v9_bc.jpg"),
    ActorModel("Emily VanCamp", "Sharon Carter / The Power Broker", "https://m.media-amazon.com/images/M/MV5BMTQ5MDc4MDk4NF5BMl5BanBnXkFtZTgwMjkwMTYwOTE@._V1_.jpg"),
    ActorModel("Julia Louis-Dreyfus", "Contessa Valentina Allegra de Fontaine", "https://cdn.britannica.com/21/181621-050-7159730A/Julia-Louis-Dreyfus-Emmy-Award.jpg"),
    ActorModel("Harrison Ford", "Rick Deckard", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/25704_v9_bc.jpg"),
    ActorModel("Rutger Hauer", "Roy Batty", "https://i.mydramalist.com/qvrJz_5c.jpg"),
    ActorModel("Sean Young", "Rachael", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/58380_v9_bb.jpg"),
    ActorModel("Edward James Olmos", "Gaff", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/18696_v9_bc.jpg"),
    ActorModel("M. Emmet Walsh", "Bryant", "https://upload.wikimedia.org/wikipedia/commons/5/5a/M_Emmet_Walsh_at_the_2009_Tribeca_Film_Festival.jpg"),
    ActorModel("Daryl Hannah", "Pris Stratton", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/727_v9_bc.jpg"),
    ActorModel("William Sanderson", "J.F. Sebastian", "https://m.media-amazon.com/images/S/amzn-author-media-prod/3ro3qfiahkjp64k8up3pjv2dl6.jpg"),
    ActorModel("Brion James", "Leon Kowalski", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/71577_v9_ba.jpg"),
    ActorModel("Joe Turkel", "Dr. Eldon Tyrell", "https://www.landmarkcinemas.com//media/413248/c7b3fedc-c07c-40ed-9250-1b01c7680d2f.jpg"),
    ActorModel("Joanna Cassidy", "Zhora Salome", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Joanna_Cassidy_LF_adjusted.jpg"),
    ActorModel("James Hong", "Hannibal Chew", "https://cdn.britannica.com/23/252423-050-9399FFDC/James-Hong-actor-2007.jpg"),
    ActorModel("Morgan Paull", "Dave Holden", "https://upload.wikimedia.org/wikipedia/en/c/c0/Morgan_Paull_640.jpg"),
    ActorModel("Hy Pyke", "Taffey Lewis", "https://www.picsofcelebrities.com/celebrity/hy-pyke/pictures/large/hy-pyke-quotes.jpg"),
    ActorModel("Daniel Craig", "James Bond", "https://image.tmdb.org/t/p/original/6j9Hu3gZsMEl6vZHNTko9yqp0Y6.jpg"),
    ActorModel("Rami Malek", "Lyutsifer Safin", "https://media.themoviedb.org/t/p/w500/ewr46CGOdsx5NzAJdIzEBz2yIQh.jpg"),
    ActorModel("Lashana Lynch", "Nomi", "https://media.themoviedb.org/t/p/w500/ypNxRag9uJ5nzPAN2um3amQK340.jpg"),
    ActorModel("Ralph Fiennes", "Gareth Mallory / M", "https://media.themoviedb.org/t/p/w500/pCnVXH1Uo2ODoOit4UXni8OD9VB.jpg"),
    ActorModel("Ben Whishaw", "Q", "https://media.themoviedb.org/t/p/w500/e74Cz65ifeNb9zHfUTvF5rTix0d.jpg"),
    ActorModel("Naomie Harris", "Eve Moneypenny", "https://media.themoviedb.org/t/p/w500/41TVAcYqKKF7PGf3x7QfaLvkLSW.jpg"),
    ActorModel("Jeffrey Wright", "Felix Leiter", "https://media.themoviedb.org/t/p/w500/yGcuHGW4glqRpOPxgiCvjcren7F.jpg"),
    ActorModel("Christoph Waltz", "Ernst Stavro Blofeld", "https://media.themoviedb.org/t/p/w500/2Hhztd4mUEV9Y25rfkXDwzL9QI9.jpg"),
    ActorModel("Joaquin Phoenix", "Arthur Fleck / Joker", "https://media.themoviedb.org/t/p/w500/dD7hrRueEZmQgGWBp7pAOOt5gLV.jpg"),
    ActorModel("Robert De Niro", "Murray Franklin", "https://media.themoviedb.org/t/p/w500/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg"),
    ActorModel("Zazie Beetz", "Sophie Dumond", "https://media.themoviedb.org/t/p/w500/sgxzT54GnvgeMnOZgpQQx9csAdd.jpg"),
    ActorModel("Frances Conroy", "Penny Fleck", "https://image.tmdb.org/t/p/original/8njcmiQzSxGcumMYG5aKnfeFupV.jpg"),
    ActorModel("Brett Cullen", "Thomas Wayne", "https://media.themoviedb.org/t/p/w500/4P6TsRcnr9MRbXlCdHitulGM5LT.jpg"),
    ActorModel("Shea Whigham", "Detectives Burke", "https://image.tmdb.org/t/p/original/suwW5Gv06Po1RzcSKVAPANrVvo3.jpg"),
    ActorModel("Bill Camp", "Detectives Garrity", "https://media.themoviedb.org/t/p/w500/yZFata0EVr7TbIAz8vZFyiDKDts.jpg"),
    ActorModel("Song Kang-ho", "Ki-taek Kim", "https://image.tmdb.org/t/p/original/kBM9UTPYXUA2RNk210DXhztLFns.jpg"),
    ActorModel("Lee Sun-kyun", "Dong-ik Park", "https://media.themoviedb.org/t/p/w500/mwF2HgyEF2UzxSvNRJEtbWlKbAj.jpg"),
    ActorModel("Cho Yeo-jeong", "Yeon-kyo Park", "https://media.themoviedb.org/t/p/w500/n7YWOoquBL9g3qEwQ2zvrQSW96L.jpg"),
    ActorModel("Choi Woo-sik", "Ki-woo Kim", "https://media.themoviedb.org/t/p/w500/6ORYWOw0BZuTwZptins0fJO6bKL.jpg"),
    ActorModel("Park So-dam", "Ki-jung Kim", "https://media.themoviedb.org/t/p/w500/gaDnEiMD5PClT9ARg1bSFyexbor.jpg"),
    ActorModel("Jang Hye-jin", "Chung-sook Kim", "https://media.themoviedb.org/t/p/w500/pZiQXSWwo9F4gncHfa1yw0CQjxk.jpg"),
    ActorModel("Park Myung-hoon", "Geun-se", "https://media.themoviedb.org/t/p/w500/5SucrxkigHss7UuJKrkfAZX5MXz.jpg"),
    ActorModel("Lee Jung-eun", "Moon-gwang Park", "https://image.tmdb.org/t/p/original/45qpdANxxvU3danQPEhpGSQM9MX.jpg"),
    ActorModel("Tim Robbins", "Andy Dufresne", "https://cdn.britannica.com/32/198332-050-7D26EAB8/Tim-Robbins-2014.jpg"),
    ActorModel("Morgan Freeman", "Ellis Boyd \"Red\" Redding", "https://static01.nyt.com/images/2023/10/26/arts/24morgan-freeman1/24morgan-freeman1-mediumSquareAt3X.jpg"),
    ActorModel("Bob Gunton", "Warden Samuel Norton", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/71567_v9_bb.jpg"),
    ActorModel("William Sadler", "Heywood", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/105148_v9_bc.jpg"),
    ActorModel("Clancy Brown", "Captain Byron Hadley", "https://m.media-amazon.com/images/M/MV5BMTUxODY3NjAzMF5BMl5BanBnXkFtZTcwMTQ5MjYwNg@@._V1_FMjpg_UX1000_.jpg"),
    ActorModel("Gil Bellows", "Tommy Williams", "https://ntvb.tmsimg.com/assets/assets/73436_v9_bb.jpg"),
    ActorModel("James Whitmore", "Brooks Hatlen", "https://upload.wikimedia.org/wikipedia/commons/9/9f/James_Whitmore.jpg"),
    ActorModel("Shameik Moore", "Miles Morales / Spider-Man", "https://media.themoviedb.org/t/p/w500/mGF5ihrMt1MCxDvEOK2MO6YcNLt.jpg"),
    ActorModel("Hailee Steinfeld", "Gwen Stacy / Spider-Woman", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/510415_v9_be.jpg"),
    ActorModel("Jake Johnson", "Peter Parker / Spider-Man Noir", "https://m.media-amazon.com/images/M/MV5BMjExMzc5NDM0Nl5BMl5BanBnXkFtZTcwOTU3MDU3OA@@._V1_FMjpg_UX1000_.jpg"),
    ActorModel("John Mulaney", "Peter Parker / Spider-Ham", "https://m.media-amazon.com/images/M/MV5BMTcyNjU3MjE3MF5BMl5BanBnXkFtZTgwNDk5MzIyMTE@._V1_.jpg"),
    ActorModel("Kimiko Glenn", "Peni Parker / SP//dr", "https://m.media-amazon.com/images/M/MV5BNDExMzc5OTc1OF5BMl5BanBnXkFtZTgwOTM1NjMwNjE@._V1_.jpg"),
    ActorModel("Nicolas Cage", "Peter Parker / Spider-Man Noir (voice)", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/258_v9_bb.jpg"),
    ActorModel("Liev Schreiber", "Kingpin / Wilson Fisk", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/39294_v9_bc.jpg"),
    ActorModel("Mahershala Ali", "Aaron Davis / Prowler", "https://hips.hearstapps.com/hmg-prod/images/mahershala_ali_photo_michael_loccisanogetty_images.jpg"),
    ActorModel("Brian Tyree Henry", "Jefferson Davis", "https://deadline.com/wp-content/uploads/2017/02/brian-tyree-henry.jpg"),
    ActorModel("Kathryn Hahn", "Olivia Octavius / Doc Ock", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/239071_v9_bb.jpg"),
    ActorModel("Lauren Vélez", "Rio Morales", "https://media.themoviedb.org/t/p/w500/98BvmTJCZHx0jPv0oNcv04Jkmfb.jpg"),
    ActorModel("Lily Tomlin", "Aunt May Parker", "https://cdn.britannica.com/38/176038-050-AD70F461/Lily-Tomlin-2011.jpg"),
    ActorModel("Chris Pine", "Peter Parker / Spider-Man (voice)", "https://i0.web.de/image/074/36618074,pd=1/chris-pine.jpg"),
    ActorModel("Zoe Kravitz", "Mary Jane Watson", "https://image.tmdb.org/t/p/w300/ppOHPQ1Boq0V22hjCXGYa1ZhM1R.jpg"),
    ActorModel("Issa Rae", "Jessica Drew / Spider-Woman", "https://m.media-amazon.com/images/M/MV5BMTUyODI3MDg1OF5BMl5BanBnXkFtZTgwMjc5NTc5MDI@._V1_.jpg"),
    ActorModel("Andy Samberg", "Ben Reilly / Scarlet Spider", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/484313_v9_bb.jpg"),
    ActorModel("Amandla Stenberg", "Margo Kess / Spider-Byte", "https://assets.teenvogue.com/photos/5cdefedcb6d5d07c211806f0/master/pass/00-promo-amandla.jpg"),
    ActorModel("Taran Killam", "Patrick O'Hara / Web-Slinger", "https://pyxis.nymag.com/v1/imgs/ea2/436/d0205914c608410e41d71dc4f02c5fa5c5-09-tarankillam.jpg"),
    ActorModel("Nic Novicki", "Peter Parker / Lego Spider-Man", "https://pbs.twimg.com/profile_images/845462865213505536/_c0je9Bu_400x400.jpg"),
    ActorModel("Josh Keaton", "Peter Parker / Spectacular Spider-Man (voice)", "https://m.media-amazon.com/images/M/MV5BMTQzMTE0NzY5OF5BMl5BanBnXkFtZTgwMTc3OTIxMjE@._V1_.jpg"),
    ActorModel("Yuri Lowenthal", "Peter Parker / Insomniac Spider-Man (voice)", "https://m.media-amazon.com/images/M/MV5BMTkwMjc2MjQ0Ml5BMl5BanBnXkFtZTcwODg5MjQwOQ@@._V1_.jpg"),
    ActorModel("Mike Rianda", "Ezekiel Sims / Spider-Therapist", "https://media.themoviedb.org/t/p/w500/1MEH4XJ7fSkwA5oCEyx3CckbIva.jpg"),
    ActorModel("Sofia Barclay", "Malala Windsor / Spider-UK", "https://asset.tix.id/wp-content/uploads/2023/05/qo8lNM993raYRxOuXVnuxD80ua7.jpg"),
    ActorModel("Danielle Perez", "Charlotte Webber / Sun-Spider", "https://pbs.twimg.com/profile_images/1217479959628763138/CTTMLegR_400x400.jpg"),
    ActorModel("Metro Boomin", "Metro Spider-Man", "https://www.ebony.com/wp-content/uploads/2023/07/25/GettyImages-1447948456-1.jpg")
)

val duneCastList = listOf(
    actorList.firstOrNull {it.name == "Timothée Chalamet"},
    actorList.firstOrNull {it.name == "Rebecca Ferguson"},
    actorList.firstOrNull {it.name == "Oscar Isaac"},
    actorList.firstOrNull {it.name == "Josh Brolin"},
    actorList.firstOrNull {it.name == "Stellan Skarsgård"},
    actorList.firstOrNull {it.name == "Dave Bautista"},
    actorList.firstOrNull {it.name == "Zendaya"},
)

val dunePartTwoCastList = listOf(
    actorList.firstOrNull {it.name == "Timothée Chalamet"},
    actorList.firstOrNull {it.name == "Rebecca Ferguson"},
    actorList.firstOrNull {it.name == "Zendaya"},
    actorList.firstOrNull {it.name == "Josh Brolin"},
    actorList.firstOrNull {it.name == "Javier Bardem"},
    actorList.firstOrNull {it.name == "Stellan Skarsgård"},
    actorList.firstOrNull {it.name == "Dave Bautista"},
    actorList.firstOrNull {it.name == "Austin Butler"},
    actorList.firstOrNull {it.name == "Florence Pugh"},
    actorList.firstOrNull {it.name == "Christopher Walken"},
    actorList.firstOrNull {it.name == "Léa Seydoux"},
)

val avengersEndgameCastList = listOf(
    actorList.firstOrNull { it.name == "Robert Downey Jr." },
    actorList.firstOrNull { it.name == "Chris Evans" },
    actorList.firstOrNull { it.name == "Mark Ruffalo" },
    actorList.firstOrNull { it.name == "Chris Hemsworth" },
    actorList.firstOrNull { it.name == "Scarlett Johansson" },
    actorList.firstOrNull { it.name == "Jeremy Renner" },
    actorList.firstOrNull { it.name == "Tom Hiddleston" },
    actorList.firstOrNull { it.name == "Samuel L. Jackson" },
    actorList.firstOrNull { it.name == "Clark Gregg" },
    actorList.firstOrNull { it.name == "Cobie Smulders" },
    actorList.firstOrNull { it.name == "Gwyneth Paltrow" },
    actorList.firstOrNull { it.name == "Stellan Skarsgård" },
)

val infinityWarCastList = listOf(
    actorList.firstOrNull { it.name == "Robert Downey Jr." },
    actorList.firstOrNull { it.name == "Chris Hemsworth" },
    actorList.firstOrNull { it.name == "Mark Ruffalo" },
    actorList.firstOrNull { it.name == "Chris Evans" },
    actorList.firstOrNull { it.name == "Scarlett Johansson" },
    actorList.firstOrNull { it.name == "Don Cheadle" },
    actorList.firstOrNull { it.name == "Benedict Cumberbatch" },
    actorList.firstOrNull { it.name == "Tom Holland" },
    actorList.firstOrNull { it.name == "Chadwick Boseman" },
    actorList.firstOrNull { it.name == "Zoe Saldana" },
    actorList.firstOrNull { it.name == "Karen Gillan" },
    actorList.firstOrNull { it.name == "Tom Hiddleston" },
    actorList.firstOrNull { it.name == "Paul Bettany" },
    actorList.firstOrNull { it.name == "Elizabeth Olsen" },
    actorList.firstOrNull { it.name == "Anthony Mackie" },
    actorList.firstOrNull { it.name == "Sebastian Stan" },
    actorList.firstOrNull { it.name == "Idris Elba" },
    actorList.firstOrNull { it.name == "Danai Gurira" },
    actorList.firstOrNull { it.name == "Benedict Wong" },
    actorList.firstOrNull { it.name == "Pom Klementieff" },
    actorList.firstOrNull { it.name == "Dave Bautista" },
    actorList.firstOrNull { it.name == "Vin Diesel" },
    actorList.firstOrNull { it.name == "Bradley Cooper" },
    actorList.firstOrNull { it.name == "Gwyneth Paltrow" },
    actorList.firstOrNull { it.name == "Benicio del Toro" },
    actorList.firstOrNull { it.name == "Josh Brolin" },
    actorList.firstOrNull { it.name == "Chris Pratt" },
    actorList.firstOrNull { it.name == "Letitia Wright" },
    actorList.firstOrNull { it.name == "Winston Duke" },
    actorList.firstOrNull { it.name == "Terry Notary" },
    actorList.firstOrNull { it.name == "Tom Vaughan-Lawlor" },
    actorList.firstOrNull { it.name == "Carrie Coon" },
    actorList.firstOrNull { it.name == "Michael James Shaw" },
    actorList.firstOrNull { it.name == "Linda Cardellini" },
    actorList.firstOrNull { it.name == "Maximiliano Hernández" },
    actorList.firstOrNull { it.name == "Sean Gunn" },
    actorList.firstOrNull { it.name == "Ross Marquand" },
    actorList.firstOrNull { it.name == "Michael Anthony Rogers" },
    actorList.firstOrNull { it.name == "Stan Lee" }
)

val avengersCastList = listOf(
    actorList.firstOrNull { it.name == "Robert Downey Jr." },
    actorList.firstOrNull { it.name == "Chris Evans" },
    actorList.firstOrNull { it.name == "Mark Ruffalo" },
    actorList.firstOrNull { it.name == "Chris Hemsworth" },
    actorList.firstOrNull { it.name == "Scarlett Johansson" },
    actorList.firstOrNull { it.name == "Jeremy Renner" },
    actorList.firstOrNull { it.name == "Tom Hiddleston" },
    actorList.firstOrNull { it.name == "Clark Gregg" },
    actorList.firstOrNull { it.name == "Cobie Smulders" },
    actorList.firstOrNull { it.name == "Stellan Skarsgård" },
    actorList.firstOrNull { it.name == "Samuel L. Jackson" },
    actorList.firstOrNull { it.name == "Gwyneth Paltrow" },
    actorList.firstOrNull { it.name == "Paul Bettany" },
    actorList.firstOrNull { it.name == "Alexis Denisof" }
)

val interstellarCastList = listOf(
    actorList.firstOrNull { it.name == "Matthew McConaughey" },
    actorList.firstOrNull { it.name == "Anne Hathaway" },
    actorList.firstOrNull { it.name == "Jessica Chastain" },
    actorList.firstOrNull { it.name == "Mackenzie Foy" },
    actorList.firstOrNull { it.name == "Michael Caine" },
    actorList.firstOrNull { it.name == "Casey Affleck" },
    actorList.firstOrNull { it.name == "Topher Grace" },
    actorList.firstOrNull { it.name == "John Lithgow" },
    actorList.firstOrNull { it.name == "David Gyasi" },
    actorList.firstOrNull { it.name == "Ellen Burstyn" }
)

val avatarCastList = listOf(
    actorList.firstOrNull { it.name == "Sam Worthington" },
    actorList.firstOrNull { it.name == "Zoe Saldana" },
    actorList.firstOrNull { it.name == "Sigourney Weaver" },
    actorList.firstOrNull { it.name == "Stephen Lang" },
    actorList.firstOrNull { it.name == "Michelle Rodriguez" },
    actorList.firstOrNull { it.name == "Giovanni Ribisi" },
    actorList.firstOrNull { it.name == "Joel David Moore" },
    actorList.firstOrNull { it.name == "CCH Pounder" },
    actorList.firstOrNull { it.name == "Wes Studi" },
    actorList.firstOrNull { it.name == "Laz Alonso" }
)

val damselCastList = listOf(
    actorList.firstOrNull { it.name == "Millie Bobby Brown" },
    actorList.firstOrNull { it.name == "Ray Winstone" },
    actorList.firstOrNull { it.name == "Angela Bassett" },
    actorList.firstOrNull { it.name == "Nick Robinson" },
    actorList.firstOrNull { it.name == "Robin Wright" },
    actorList.firstOrNull { it.name == "Brooke Carter" },
    actorList.firstOrNull { it.name == "Milo Twomey" },
    actorList.firstOrNull { it.name == "Nicole Joseph" },
)

val barbieCastList = listOf(
    actorList.firstOrNull { it.name == "Margot Robbie" },
    actorList.firstOrNull { it.name == "Ryan Gosling" },
    actorList.firstOrNull { it.name == "Issa Rae" },
    actorList.firstOrNull { it.name == "Kate McKinnon" },
    actorList.firstOrNull { it.name == "Alexandra Shipp" },
    actorList.firstOrNull { it.name == "Emma Mackey" },
    actorList.firstOrNull { it.name == "Hari Nef" },
    actorList.firstOrNull { it.name == "Sharon Rooney" },
    actorList.firstOrNull { it.name == "Ana Cruz Kayne" },
    actorList.firstOrNull { it.name == "Ritu Arya" },
    actorList.firstOrNull { it.name == "Dua Lipa" },
    actorList.firstOrNull { it.name == "Nicola Coughlan" },
    actorList.firstOrNull { it.name == "Emerald Fennell" },
    actorList.firstOrNull { it.name == "Simu Liu" },
    actorList.firstOrNull { it.name == "Kingsley Ben-Adir" },
    actorList.firstOrNull { it.name == "Ncuti Gatwa" },
    actorList.firstOrNull { it.name == "Scott Evans" },
    actorList.firstOrNull { it.name == "John Cena" },
    actorList.firstOrNull { it.name == "Michael Cera" },
    actorList.firstOrNull { it.name == "Helen Mirren" }
)

val falconAndWinterSoldierCastList = listOf(
    actorList.firstOrNull { it.name == "Anthony Mackie" },
    actorList.firstOrNull { it.name == "Sebastian Stan" },
    actorList.firstOrNull { it.name == "Daniel Brühl" },
    actorList.firstOrNull { it.name == "Emily VanCamp" },
    actorList.firstOrNull { it.name == "Wyatt Russell" },
    actorList.firstOrNull { it.name == "Desmond Chiam" },
    actorList.firstOrNull { it.name == "Miki Ishikawa" },
    actorList.firstOrNull { it.name == "Adepero Oduye" },
    actorList.firstOrNull { it.name == "Carl Lumbly" },
    actorList.firstOrNull { it.name == "Danny Ramirez" }
)

val bladeRunnerCastList = listOf(
    actorList.firstOrNull { it.name == "Harrison Ford" },
    actorList.firstOrNull { it.name == "Rutger Hauer" },
    actorList.firstOrNull { it.name == "Sean Young" },
    actorList.firstOrNull { it.name == "Edward James Olmos" },
    actorList.firstOrNull { it.name == "M. Emmet Walsh" },
    actorList.firstOrNull { it.name == "Daryl Hannah" },
    actorList.firstOrNull { it.name == "William Sanderson" },
    actorList.firstOrNull { it.name == "Brion James" },
    actorList.firstOrNull { it.name == "Joe Turkel" },
    actorList.firstOrNull { it.name == "Joanna Cassidy" },
    actorList.firstOrNull { it.name == "James Hong" },
    actorList.firstOrNull { it.name == "Morgan Paull" },
    actorList.firstOrNull { it.name == "Hy Pyke" }
)

val bladeRunner2049CastList = listOf(
    actorList.firstOrNull { it.name == "Ryan Gosling" },
    actorList.firstOrNull { it.name == "Harrison Ford" },
    actorList.firstOrNull { it.name == "Ana de Armas" },
    actorList.firstOrNull { it.name == "Jared Leto" },
    actorList.firstOrNull { it.name == "Robin Wright" },
    actorList.firstOrNull { it.name == "Sylvia Hoeks" },
    actorList.firstOrNull { it.name == "Dave Bautista" },
    actorList.firstOrNull { it.name == "Mackenzie Davis" },
    actorList.firstOrNull { it.name == "Carla Juri" },
    actorList.firstOrNull { it.name == "Lennie James" }
)

val noTimeToDieCastList = listOf(
    actorList.firstOrNull { it.name == "Daniel Craig" },
    actorList.firstOrNull { it.name == "Léa Seydoux" },
    actorList.firstOrNull { it.name == "Rami Malek" },
    actorList.firstOrNull { it.name == "Lashana Lynch" },
    actorList.firstOrNull { it.name == "Ralph Fiennes" },
    actorList.firstOrNull { it.name == "Ben Whishaw" },
    actorList.firstOrNull { it.name == "Naomie Harris" },
    actorList.firstOrNull { it.name == "Jeffrey Wright" },
    actorList.firstOrNull { it.name == "Christoph Waltz" }
)

val jokerCastList = listOf(
    actorList.firstOrNull { it.name == "Joaquin Phoenix" },
    actorList.firstOrNull { it.name == "Robert De Niro" },
    actorList.firstOrNull { it.name == "Zazie Beetz" },
    actorList.firstOrNull { it.name == "Frances Conroy" },
    actorList.firstOrNull { it.name == "Brett Cullen" },
    actorList.firstOrNull { it.name == "Shea Whigham" },
    actorList.firstOrNull { it.name == "Bill Camp" }
)

val parasiteCastList = listOf(
    actorList.firstOrNull { it.name == "Song Kang-ho" },
    actorList.firstOrNull { it.name == "Lee Sun-kyun" },
    actorList.firstOrNull { it.name == "Cho Yeo-jeong" },
    actorList.firstOrNull { it.name == "Choi Woo-sik" },
    actorList.firstOrNull { it.name == "Park So-dam" },
    actorList.firstOrNull { it.name == "Jang Hye-jin" },
    actorList.firstOrNull { it.name == "Park Myung-hoon" },
    actorList.firstOrNull { it.name == "Lee Jung-eun" }
)

val shawshankCastList = listOf(
    actorList.firstOrNull { it.name == "Tim Robbins" },
    actorList.firstOrNull { it.name == "Morgan Freeman" },
    actorList.firstOrNull { it.name == "Bob Gunton" },
    actorList.firstOrNull { it.name == "William Sadler" },
    actorList.firstOrNull { it.name == "Clancy Brown" },
    actorList.firstOrNull { it.name == "Gil Bellows" },
    actorList.firstOrNull { it.name == "James Whitmore" }
)

val intoTheSpiderVerse = listOf(
    actorList.firstOrNull { it.name == "Shameik Moore" },
    actorList.firstOrNull { it.name == "Hailee Steinfeld" },
    actorList.firstOrNull { it.name == "Jake Johnson" },
    actorList.firstOrNull { it.name == "John Mulaney" },
    actorList.firstOrNull { it.name == "Kimiko Glenn" },
    actorList.firstOrNull { it.name == "Nicolas Cage" },
    actorList.firstOrNull { it.name == "Liev Schreiber" },
    actorList.firstOrNull { it.name == "Mahershala Ali" },
    actorList.firstOrNull { it.name == "Brian Tyree Henry" },
    actorList.firstOrNull { it.name == "Kathryn Hahn" },
    actorList.firstOrNull { it.name == "Lauren Vélez" },
    actorList.firstOrNull { it.name == "Lily Tomlin" },
    actorList.firstOrNull { it.name == "Chris Pine" },
    actorList.firstOrNull { it.name == "Zoe Kravitz" }
)

val acrossTheSpiderVerse = listOf(
    actorList.firstOrNull { it.name == "Shameik Moore" },
    actorList.firstOrNull { it.name == "Hailee Steinfeld" },
    actorList.firstOrNull { it.name == "Jake Johnson" },
    actorList.firstOrNull { it.name == "John Mulaney" },
    actorList.firstOrNull { it.name == "Kimiko Glenn" },
    actorList.firstOrNull { it.name == "Nicolas Cage" },
    actorList.firstOrNull { it.name == "Liev Schreiber" },
    actorList.firstOrNull { it.name == "Mahershala Ali" },
    actorList.firstOrNull { it.name == "Brian Tyree Henry" },
    actorList.firstOrNull { it.name == "Kathryn Hahn" },
    actorList.firstOrNull { it.name == "Lauren Vélez" },
    actorList.firstOrNull { it.name == "Lily Tomlin" },
    actorList.firstOrNull { it.name == "Chris Pine" },
    actorList.firstOrNull { it.name == "Zoe Kravitz" },
    actorList.firstOrNull { it.name == "Oscar Isaac" },
    actorList.firstOrNull { it.name == "Issa Rae" },
    actorList.firstOrNull { it.name == "Andy Samberg" },
    actorList.firstOrNull { it.name == "Amandla Stenberg" },
    actorList.firstOrNull { it.name == "Taran Killam" },
    actorList.firstOrNull { it.name == "Nic Novicki" },
    actorList.firstOrNull { it.name == "Josh Keaton" },
    actorList.firstOrNull { it.name == "Yuri Lowenthal" },
    actorList.firstOrNull { it.name == "Mike Rianda" },
    actorList.firstOrNull { it.name == "Sofia Barclay" },
    actorList.firstOrNull { it.name == "Danielle Perez" },
    actorList.firstOrNull { it.name == "Metro Boomin" }
)